var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var d=0;return function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var d="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,m){a!=Array.prototype&&a!=Object.prototype&&(a[d]=m.value)};
$jscomp.polyfill=function(a,d,m,k){if(d){m=$jscomp.global;a=a.split(".");for(k=0;k<a.length-1;k++){var f=a[k];f in m||(m[f]={});m=m[f]}a=a[a.length-1];k=m[a];d=d(k);d!=k&&null!=d&&$jscomp.defineProperty(m,a,{configurable:!0,writable:!0,value:d})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function m(b){return b instanceof f?b:new f(function(a,d){a(b)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(b){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(b);return this};d.prototype.asyncExecuteBatch_=function(){var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})};var k=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(b){k(b,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var b=this.batch_;this.batch_=[];for(var a=0;a<b.length;++a){var d=b[a];b[a]=null;try{d()}catch(r){this.asyncThrow_(r)}}}this.batch_=null};d.prototype.asyncThrow_=function(b){this.asyncExecuteFunction(function(){throw b;})};var f=function(b){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{b(a.resolve,a.reject)}catch(w){a.reject(w)}};f.prototype.createResolveAndReject_=
function(){function b(b){return function(f){d||(d=!0,b.call(a,f))}}var a=this,d=!1;return{resolve:b(this.resolveTo_),reject:b(this.reject_)}};f.prototype.resolveTo_=function(b){if(b===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof f)this.settleSameAsPromise_(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(b):this.fulfill_(b)}};f.prototype.resolveToNonPromiseObj_=function(b){var a=
void 0;try{a=b.then}catch(w){this.reject_(w);return}"function"==typeof a?this.settleSameAsThenable_(a,b):this.fulfill_(b)};f.prototype.reject_=function(b){this.settle_(2,b)};f.prototype.fulfill_=function(b){this.settle_(1,b)};f.prototype.settle_=function(b,a){if(0!=this.state_)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.state_);this.state_=b;this.result_=a;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var b=
0;b<this.onSettledCallbacks_.length;++b)n.asyncExecute(this.onSettledCallbacks_[b]);this.onSettledCallbacks_=null}};var n=new d;f.prototype.settleSameAsPromise_=function(b){var a=this.createResolveAndReject_();b.callWhenSettled_(a.resolve,a.reject)};f.prototype.settleSameAsThenable_=function(a,d){var b=this.createResolveAndReject_();try{a.call(d,b.resolve,b.reject)}catch(r){b.reject(r)}};f.prototype.then=function(a,d){function b(a,b){return"function"==typeof a?function(b){try{m(a(b))}catch(L){k(L)}}:
b}var m,k,y=new f(function(a,b){m=a;k=b});this.callWhenSettled_(b(a,m),b(d,k));return y};f.prototype.catch=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,d){function b(){switch(f.state_){case 1:a(f.result_);break;case 2:d(f.result_);break;default:throw Error("Unexpected state: "+f.state_);}}var f=this;null==this.onSettledCallbacks_?n.asyncExecute(b):this.onSettledCallbacks_.push(b)};f.resolve=m;f.reject=function(a){return new f(function(b,d){d(a)})};f.race=function(a){return new f(function(b,
d){for(var f=$jscomp.makeIterator(a),k=f.next();!k.done;k=f.next())m(k.value).callWhenSettled_(b,d)})};f.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?m([]):new f(function(a,f){function k(b){return function(d){n[b]=d;t--;0==t&&a(n)}}var n=[],t=0;do n.push(void 0),t++,m(d.value).callWhenSettled_(k(n.length-1),f),d=b.next();while(!d.done)})};return f},"es6","es3");
$jscomp.findInternal=function(a,d,m){a instanceof String&&(a=String(a));for(var k=a.length,f=0;f<k;f++){var n=a[f];if(d.call(m,n,f,a))return{i:f,v:n}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,m){return $jscomp.findInternal(this,a,m).v}},"es6","es3");function asyncGeneratorStep(a,d,m,k,f,n,b){try{var y=a[n](b),w=y.value}catch(r){m(r);return}y.done?d(w):Promise.resolve(w).then(k,f)}
function _asyncToGenerator(a){return function(){var d=this,m=arguments;return new Promise(function(k,f){function n(a){asyncGeneratorStep(y,k,f,n,b,"next",a)}function b(a){asyncGeneratorStep(y,k,f,n,b,"throw",a)}var y=a.apply(d,m);n(void 0)})}}function _typeof(a){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};return _typeof(a)}var _regenerator;
(function(){var a=function(a){function d(a,l,b,c){l=Object.create((l&&l.prototype instanceof f?l:f).prototype);c=new t(c||[]);l._invoke=r(a,b,c);return l}function k(a,l,b){try{return{type:"normal",arg:a.call(l,b)}}catch(P){return{type:"throw",arg:P}}}function f(){}function n(){}function b(){}function y(a){["next","throw","return"].forEach(function(l){a[l]=function(a){return this._invoke(l,a)}})}function w(a,l){function p(b,c,h,M){b=k(a[b],a,c);if("throw"===b.type)M(b.arg);else{var g=b.arg;return(b=
g.value)&&"object"===_typeof(b)&&q.call(b,"__await")?l.resolve(b.__await).then(function(a){p("next",a,h,M)},function(a){p("throw",a,h,M)}):l.resolve(b).then(function(a){g.value=a;h(g)},function(a){return p("throw",a,h,M)})}}var b;this._invoke=function(a,c){function h(){return new l(function(b,l){p(a,c,b,l)})}return b=b?b.then(h,h):h()}}function r(a,b,c){var l=g;return function(p,e){if(l===N)throw Error("Generator is already running");if(l===x){if("throw"===p)throw e;return L()}c.method=p;for(c.arg=
e;;){if(p=c.delegate)if(p=B(p,c)){if(p===E)continue;return p}if("next"===c.method)c.sent=c._sent=c.arg;else if("throw"===c.method){if(l===g)throw l=x,c.arg;c.dispatchException(c.arg)}else"return"===c.method&&c.abrupt("return",c.arg);l=N;p=k(a,b,c);if("normal"===p.type){l=c.done?x:h;if(p.arg===E)continue;return{value:p.arg,done:c.done}}"throw"===p.type&&(l=x,c.method="throw",c.arg=p.arg)}}}function B(a,l){var b=a.iterator[l.method];if(b===e){l.delegate=null;if("throw"===l.method){if(a.iterator["return"]&&
(l.method="return",l.arg=e,B(a,l),"throw"===l.method))return E;l.method="throw";l.arg=new TypeError("The iterator does not provide a 'throw' method")}return E}b=k(b,a.iterator,l.arg);if("throw"===b.type)return l.method="throw",l.arg=b.arg,l.delegate=null,E;b=b.arg;if(!b)return l.method="throw",l.arg=new TypeError("iterator result is not an object"),l.delegate=null,E;if(b.done)l[a.resultName]=b.value,l.next=a.nextLoc,"return"!==l.method&&(l.method="next",l.arg=e);else return b;l.delegate=null;return E}
function K(a){var b={tryLoc:a[0]};1 in a&&(b.catchLoc=a[1]);2 in a&&(b.finallyLoc=a[2],b.afterLoc=a[3]);this.tryEntries.push(b)}function J(a){var b=a.completion||{};b.type="normal";delete b.arg;a.completion=b}function t(a){this.tryEntries=[{tryLoc:"root"}];a.forEach(K,this);this.reset(!0)}function C(a){if(a){var b=a[O];if(b)return b.call(a);if("function"===typeof a.next)return a;if(!isNaN(a.length)){var c=-1;b=function A(){for(;++c<a.length;)if(q.call(a,c))return A.value=a[c],A.done=!1,A;A.value=
e;A.done=!0;return A};return b.next=b}}return{next:L}}function L(){return{value:e,done:!0}}var F=Object.prototype,q=F.hasOwnProperty,e,v="function"===typeof Symbol?Symbol:{},O=v.iterator||"@@iterator",D=v.asyncIterator||"@@asyncIterator",c=v.toStringTag||"@@toStringTag";a.wrap=d;var g="suspendedStart",h="suspendedYield",N="executing",x="completed",E={};v={};v[O]=function(){return this};var I=Object.getPrototypeOf;(I=I&&I(I(C([]))))&&I!==F&&q.call(I,O)&&(v=I);var u=b.prototype=f.prototype=Object.create(v);
n.prototype=u.constructor=b;b.constructor=n;b[c]=n.displayName="GeneratorFunction";a.isGeneratorFunction=function(a){return(a="function"===typeof a&&a.constructor)?a===n||"GeneratorFunction"===(a.displayName||a.name):!1};a.mark=function(a){Object.setPrototypeOf?Object.setPrototypeOf(a,b):(a.__proto__=b,c in a||(a[c]="GeneratorFunction"));a.prototype=Object.create(u);return a};a.awrap=function(a){return{__await:a}};y(w.prototype);w.prototype[D]=function(){return this};a.AsyncIterator=w;a.async=function(b,
c,h,g,e){void 0===e&&(e=Promise);var l=new w(d(b,c,h,g),e);return a.isGeneratorFunction(c)?l:l.next().then(function(a){return a.done?a.value:l.next()})};y(u);u[c]="Generator";u[O]=function(){return this};u.toString=function(){return"[object Generator]"};a.keys=function(a){var b=[],c;for(c in a)b.push(c);b.reverse();return function A(){for(;b.length;){var c=b.pop();if(c in a)return A.value=c,A.done=!1,A}A.done=!0;return A}};a.values=C;t.prototype={constructor:t,reset:function(a){this.next=this.prev=
0;this.sent=this._sent=e;this.done=!1;this.delegate=null;this.method="next";this.arg=e;this.tryEntries.forEach(J);if(!a)for(var b in this)"t"===b.charAt(0)&&q.call(this,b)&&!isNaN(+b.slice(1))&&(this[b]=e)},stop:function(){this.done=!0;var a=this.tryEntries[0].completion;if("throw"===a.type)throw a.arg;return this.rval},dispatchException:function(a){function b(b,g){v.type="throw";v.arg=a;c.next=b;g&&(c.method="next",c.arg=e);return!!g}if(this.done)throw a;for(var c=this,h=this.tryEntries.length-1;0<=
h;--h){var g=this.tryEntries[h],v=g.completion;if("root"===g.tryLoc)return b("end");if(g.tryLoc<=this.prev){var f=q.call(g,"catchLoc"),d=q.call(g,"finallyLoc");if(f&&d){if(this.prev<g.catchLoc)return b(g.catchLoc,!0);if(this.prev<g.finallyLoc)return b(g.finallyLoc)}else if(f){if(this.prev<g.catchLoc)return b(g.catchLoc,!0)}else if(d){if(this.prev<g.finallyLoc)return b(g.finallyLoc)}else throw Error("try statement without catch or finally");}}},abrupt:function(a,b){for(var c=this.tryEntries.length-
1;0<=c;--c){var g=this.tryEntries[c];if(g.tryLoc<=this.prev&&q.call(g,"finallyLoc")&&this.prev<g.finallyLoc){var h=g;break}}h&&("break"===a||"continue"===a)&&h.tryLoc<=b&&b<=h.finallyLoc&&(h=null);c=h?h.completion:{};c.type=a;c.arg=b;return h?(this.method="next",this.next=h.finallyLoc,E):this.complete(c)},complete:function(a,b){if("throw"===a.type)throw a.arg;"break"===a.type||"continue"===a.type?this.next=a.arg:"return"===a.type?(this.rval=this.arg=a.arg,this.method="return",this.next="end"):"normal"===
a.type&&b&&(this.next=b);return E},finish:function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.finallyLoc===a)return this.complete(c.completion,c.afterLoc),J(c),E}},"catch":function(a){for(var b=this.tryEntries.length-1;0<=b;--b){var c=this.tryEntries[b];if(c.tryLoc===a){a=c.completion;if("throw"===a.type){var g=a.arg;J(c)}return g}}throw Error("illegal catch attempt");},delegateYield:function(a,b,c){this.delegate={iterator:C(a),resultName:b,nextLoc:c};"next"===this.method&&
(this.arg=e);return E}};return a}("object"===("undefined"===typeof module?"undefined":_typeof(module))?module.exports:{});try{_regenerator=a}catch(d){Function("r","_regenerator = r")(a)}})();
(function(){function a(){a=_asyncToGenerator(_regenerator.mark(function q(a){return _regenerator.wrap(function(a){for(;;)switch(a.prev=a.next){case 0:return a.prev=0,a.next=3,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"LogClear",{}),type:"POST",dataType:"json",cache:!1});case 3:a.next=7;break;case 5:a.prev=5,a.t0=a["catch"](0);case 7:case "end":return a.stop()}},q,this,[[0,5]])}));return a.apply(this,arguments)}function d(){d=_asyncToGenerator(_regenerator.mark(function e(a,
b){var v,f,d,c,g,h;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:v=jQuery(a.parentNode).closest(".blck").first();f=v.find(".seraph_accel_spinner");v.find(".content");d=v.find('input[type="button"]:not(.cancel)');c=v.find('input[type="button"].cancel');if(!b){e.next=23;break}d.prop("disabled",!0);f.show();seraph_accel.Manager._int.notRefreshStat=!0;g=null;e.prev=10;e.next=13;return jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"UpdateStatBegin",
{}),cache:!1,dataType:"json"});case 13:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(g=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=20;break;case 17:e.prev=17,e.t0=e["catch"](10),g="HTTP "+e.t0.status;case 20:return g&&(alert(g),d.prop("disabled",!1),f.hide()),delete seraph_accel.Manager._int.notRefreshStat,e.abrupt("return");case 23:return c.prop("disabled",!0),seraph_accel.Manager._int.notRefreshStat=!0,g=null,e.prev=26,e.next=29,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"UpdateStatCancel",{}),type:"POST",cache:!1,dataType:"json"});case 29:h=e.sent;seraph_accel.Gen.hr.Fail(h)&&(g=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),h));e.next=37;break;case 33:e.prev=33,e.t1=e["catch"](26),g="HTTP "+e.t1.status,c.prop("disabled",!1);case 37:g&&alert(g),delete seraph_accel.Manager._int.notRefreshStat;case 39:case "end":return e.stop()}},e,this,[[10,17],[26,33]])}));return d.apply(this,arguments)}function m(a){switch(a){case 0:return t("OpDescr_Invalidate",
"admin.Manage","seraphinite-accelerator");case 2:return t("OpDescr_Delete","admin.Manage","seraphinite-accelerator");case 10:return t("OpDescr_SrvDel","admin.Manage","seraphinite-accelerator")}return""+a}function k(){k=_asyncToGenerator(_regenerator.mark(function q(a){var b,v,f,d;return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return b=jQuery(a.parentNode).closest(".blck").first(),v=b.find('input[type="button"].cancel'),v.prop("disabled",!0),f=null,c.prev=4,c.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"PostUpdCancel",{}),type:"POST",cache:!1,dataType:"json"});case 7:d=c.sent;seraph_accel.Gen.hr.Fail(d)&&(f=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),d));c.next=14;break;case 11:c.prev=11,c.t0=c["catch"](4),f="HTTP "+c.t0.status;case 14:f&&alert(f);case 15:case "end":return c.stop()}},q,this,[[4,11]])}));return k.apply(this,arguments)}function f(){f=_asyncToGenerator(_regenerator.mark(function q(a){var b,f,d,D;return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return b=
jQuery(a.parentNode).closest(".blck").first(),f=b.find('input[type="button"].cancel'),f.prop("disabled",!0),d=null,c.prev=4,c.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"ScheUpdCancel",{}),type:"POST",cache:!1,dataType:"json"});case 7:D=c.sent;seraph_accel.Gen.hr.Fail(D)&&(d=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),D));c.next=14;break;case 11:c.prev=11,c.t0=c["catch"](4),d="HTTP "+c.t0.status;case 14:d&&alert(d);case 15:case "end":return c.stop()}},
q,this,[[4,11]])}));return f.apply(this,arguments)}function n(){n=_asyncToGenerator(_regenerator.mark(function e(a,b){var d,f,D,c,g,h,q,x,k,F;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return d=jQuery(a.parentNode).closest(".blck").first(),f=d.find(".seraph_accel_spinner"),D=d.find(".descr"),c=d.find('input[type="button"]:not(.cancel)'),g=d.find('input[type="button"].cancel'),h=d.find(".type").val(),q=seraph_accel.Gen.StrReplaceAll(String(d.find(".uri").val()),["\r",
"\n","*"],["",";","{ASTRSK}"]),f.show(),D.show(),D.text(m(b)),c.prop("disabled",!0),g.prop("disabled",!1),seraph_accel.Manager._int.notRefreshOp=!0,x={cache:!1,dataType:"json"},512>q.length?x.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:h,op:b,uri:q}):(x.url=seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpBegin",{type:h,op:b}),x.type="POST",x.contentType="application/x-www-form-urlencoded",x.data="uri="+encodeURIComponent(q)),
k=null,e.prev=16,e.next=19,jQuery.ajax(x);case 19:F=e.sent;seraph_accel.Gen.hr.Fail(F)&&(k=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),F));e.next=26;break;case 23:e.prev=23,e.t0=e["catch"](16),k="HTTP "+e.t0.status;case 26:k&&alert(k),delete seraph_accel.Manager._int.notRefreshOp;case 28:case "end":return e.stop()}},e,this,[[16,23]])}));return n.apply(this,arguments)}function b(){b=_asyncToGenerator(_regenerator.mark(function e(a,b){var d,f,k,c;return _regenerator.wrap(function(g){for(;;)switch(g.prev=
g.next){case 0:return d=jQuery(a.parentNode).closest(".blck").first(),f=d.find('input[type="button"].cancel'),f.prop("disabled",!0),k=null,g.prev=4,g.next=7,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"CacheOpCancel",{op:b}),type:"POST",cache:!1,dataType:"json"});case 7:c=g.sent;seraph_accel.Gen.hr.Fail(c)&&(k=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),c));g.next=14;break;case 11:g.prev=11,g.t0=g["catch"](4),k="HTTP "+g.t0.status;case 14:k&&
alert(k);case 15:case "end":return g.stop()}},e,this,[[4,11]])}));return b.apply(this,arguments)}function y(){y=_asyncToGenerator(_regenerator.mark(function e(a,b){var d,f,k,c,g;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:return d=jQuery(a.parentNode).closest(".blck").first(),f=d.find(".seraph_accel_spinner"),k=d.find('input[type="button"]'),f.show(),k.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,c=null,h.prev=7,h.next=10,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"QueueDelete",{allSites:b?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 10:g=h.sent;seraph_accel.Gen.hr.Fail(g)&&(c=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));h.next=17;break;case 14:h.prev=14,h.t0=h["catch"](7),c="HTTP "+h.t0.status;case 17:c&&(alert(c),f.hide(),k.prop("disabled",!1)),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 19:case "end":return h.stop()}},e,this,[[7,14]])}));return y.apply(this,arguments)}function w(){w=_asyncToGenerator(_regenerator.mark(function e(a,
b){var d,f,k,c,g;return _regenerator.wrap(function(h){for(;;)switch(h.prev=h.next){case 0:if(confirm(t("ItemCancelConfirm","admin.Manage_Queue","seraphinite-accelerator"))){h.next=2;break}return h.abrupt("return");case 2:return d=jQuery(a.parentNode).closest(".blck").first(),f=d.find(".seraph_accel_spinner"),k=d.find('input[type="button"]'),f.show(),k.prop("disabled",!0),seraph_accel.Manager._int.notRefreshQueueDeleting=!0,c=null,h.prev=9,h.next=12,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+
"QueueItemCancel",{pc:b}),type:"GET",cache:!1,dataType:"json"});case 12:g=h.sent;seraph_accel.Gen.hr.Fail(g)&&(c=C(t("OpSrvErr_%1$08X","admin.Manage","seraphinite-accelerator"),g));h.next=19;break;case 16:h.prev=16,h.t0=h["catch"](9),c="HTTP "+h.t0.status;case 19:c&&alert(c),f.hide(),k.prop("disabled",!1),delete seraph_accel.Manager._int.notRefreshQueueDeleting;case 23:case "end":return h.stop()}},e,this,[[9,16]])}));return w.apply(this,arguments)}function r(){r=_asyncToGenerator(_regenerator.mark(function e(a,
b){var d,f,k,c;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:c=function(){c=_asyncToGenerator(_regenerator.mark(function N(){return _regenerator.wrap(function(c){for(;;)switch(c.prev=c.next){case 0:return c.next=2,seraph_accel.Manager._int.OnDataRefresh(a,b);case 2:f();case 3:case "end":return c.stop()}},N,this)}));return c.apply(this,arguments)},k=function(){return c.apply(this,arguments)},f=function(){var a=1E3*parseInt(d.val(),10);100>a&&(a=100);clearTimeout(seraph_accel.Manager._int.refreshTimer);
seraph_accel.Manager._int.refreshTimer=setTimeout(k,a)},d=jQuery(a).find("#queue .tmDataRefresh"),d.on("change",f),k();case 6:case "end":return g.stop()}},e,this)}));return r.apply(this,arguments)}function B(){B=_asyncToGenerator(_regenerator.mark(function e(a,b){var d,f,k,c,g,h,q,x,n,F,u,p,l,w,y,A,r,G,H,z,B;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return d=jQuery(a).find("#status").first(),f=jQuery(a).find("#stat").first(),k=f.find(".seraph_accel_spinner"),c=f.find('input[type="button"]:not(.cancel)'),
g=f.find('input[type="button"].cancel'),h=jQuery(a).find("#operate").first(),q=h.find(".seraph_accel_spinner"),x=h.find(".descr"),n=h.find('input[type="button"]:not(.cancel)'),F=h.find('input[type="button"].cancel'),u=jQuery(a).find("#queue").first(),p=u.find(".content"),l=u.find(".maxItems"),w=u.find(".seraph_accel_spinner"),y=u.find('input[type="button"]'),A=u.find(".descrNums"),e.prev=16,e.next=19,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"GetData",
{nMaxQueueItems:l.val(),allSites:b?!0:void 0}),type:"GET",cache:!1,dataType:"json"});case 19:z=e.sent;e.next=24;break;case 22:e.prev=22,e.t0=e["catch"](16);case 24:if(z){e.next=26;break}return e.abrupt("return");case 26:if(!b){for(B in z.status.cont)d.find('[data-id-cont="'+B+'"]').html(z.status.cont[B]);seraph_accel.Manager._int.notRefreshPostUpd||(r=d.find(".blck.postupd .seraph_accel_spinner"),G=d.find('.blck.postupd input[type="button"]:not(.cancel)'),H=d.find('.blck.postupd input[type="button"].cancel'),
z.status.postUpd?(r.show(),G.prop("disabled",!0),H.prop("disabled",!1)):(r.hide(),G.prop("disabled",!1),H.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshScheUpd||(r=d.find(".blck.scheupd .seraph_accel_spinner"),G=d.find('.blck.scheupd input[type="button"]:not(.cancel)'),H=d.find('.blck.scheupd input[type="button"].cancel'),z.status.scheUpd?(r.show(),G.prop("disabled",!0),H.prop("disabled",!1)):(r.hide(),G.prop("disabled",!1),H.prop("disabled",!0)));seraph_accel.Manager._int.notRefreshCleanup||
(r=d.find(".blck.cleanup .seraph_accel_spinner"),G=d.find('.blck.cleanup input[type="button"]:not(.cancel)'),H=d.find('.blck.cleanup input[type="button"].cancel'),z.status.cleanUp?(r.show(),G.prop("disabled",!0),H.prop("disabled",!1)):(r.hide(),G.prop("disabled",!1),H.prop("disabled",!0)))}if(!b&&!seraph_accel.Manager._int.notRefreshStat)for(B in z.stat.isUpdating?(k.show(),c.prop("disabled",!0),g.prop("disabled",!1)):(k.hide(),c.prop("disabled",!1),g.prop("disabled",!0)),z.stat.cont)f.find('[data-id-cont="'+
B+'"]').html(z.stat.cont[B]);b||seraph_accel.Manager._int.notRefreshOp||(null===z.curOp&&(z.curOp=void 0),void 0!==z.curOp?(q.show(),x.show(),x.text(m(z.curOp)),n.prop("disabled",!0),F.prop("disabled",!1)):(q.hide(),x.hide(),n.prop("disabled",!1),F.prop("disabled",!0),x.text("")));p.html(z.queue.content);A.text(C(t("QueueNumsDescr_%1$u%2$u","admin.Manage","seraphinite-accelerator"),z.queue.nums.nInitial,z.queue.nums.nInProgress));seraph_accel.Manager._int.notRefreshQueueDeleting||(w.hide(),y.prop("disabled",
!1));case 32:case "end":return e.stop()}},e,this,[[16,22]])}));return B.apply(this,arguments)}function K(){K=_asyncToGenerator(_regenerator.mark(function q(a){var b,d,f,k,c,g,h,m;return _regenerator.wrap(function(e){for(;;)switch(e.prev=e.next){case 0:return b=jQuery(a.parentNode).closest(".blck").first(),d=b.find(".url"),f=b.find(".messages"),k=b.find(".seraph_accel_spinner"),c=b.find('input[type="button"]'),g=0,b.find(".liteChk").prop("checked")&&(g|=1),b.find(".medChk").prop("checked")&&(g|=2),
b.find(".tidyChk").prop("checked")&&(g|=524288),f.empty(),k.show(),c.prop("disabled",!0),e.prev=12,e.next=15,jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"HtmlCheck",{url:d.val(),norm:g}),type:"POST",dataType:"json",cache:!1});case 15:h=e.sent;e.next=21;break;case 18:e.prev=18,e.t0=e["catch"](12),h={err:e.t0.statusText};case 21:k.hide();c.prop("disabled",!1);if(!h.err){e.next=26;break}f.append(seraph_accel.Ui.LogItem("error",h.err));return e.abrupt("return");
case 26:for(m in h.list)m=h.list[m],f.append(seraph_accel.Ui.LogItem(m.severity,m.text));case 27:case "end":return e.stop()}},q,this,[[12,18]])}));return K.apply(this,arguments)}var J=seraph_accel.Wp.Loc.GetApi(),t=J._x,C=J.sprintf;seraph_accel.Settings={_int:{StrItem_OnAdd:function(a){function b(a){(a=a.trim())&&seraph_accel.Ui.TokensList.AddItem(f[0],a)}var d=1<arguments.length&&void 0!==arguments[1]?arguments[1]:",",e=jQuery(a.parentNode).closest(".blck").first(),f=e.find(".vals");e=e.find(".val");
d?e.val().split(d).forEach(b):b(e.val());e.val("")},OnUpdateCssAuto:function(a){seraph_accel.Ui.ComboShowDependedItems(a,jQuery(a.parentNode).closest(".blck").first().get(0))},OnLogClear:function(b){return a.apply(this,arguments)}}};seraph_accel.Manager={_int:{OnStatOp:function(a,b){return d.apply(this,arguments)},OnCacheOp:function(a,b){return n.apply(this,arguments)},OnCacheOpCancel:function(a,d){return b.apply(this,arguments)},OnPostUpdCancel:function(a){return k.apply(this,arguments)},OnScheUpdCancel:function(a){return f.apply(this,
arguments)},OnQueueDel:function(a,b){return y.apply(this,arguments)},OnQueueItemCancel:function(a,b){return w.apply(this,arguments)},OnDataRefreshInit:function(a,b){return r.apply(this,arguments)},OnDataRefresh:function(a,b){return B.apply(this,arguments)},OnHtmlCheck:function(a){return K.apply(this,arguments)}}};(function(){function a(a){return b.apply(this,arguments)}function b(){b=_asyncToGenerator(_regenerator.mark(function D(a){var b,d;return _regenerator.wrap(function(c){for(;;)switch(c.prev=
c.next){case 0:return b={},c.prev=1,seraph_accel.SelfDiag._int.curAjax=jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(seraph_accel.Plugin.GetAdminApiUrl()+"SelfDiag_"+a,{}),cache:!1,dataType:"json"}),c.next=5,seraph_accel.SelfDiag._int.curAjax;case 5:b=c.sent;delete seraph_accel.SelfDiag._int.curAjax;c.next=14;break;case 9:c.prev=9,c.t0=c["catch"](1),delete seraph_accel.SelfDiag._int.curAjax,0===c.t0.status?b.hr=seraph_accel.Gen.hr.S_ABORTED:(b.hr=seraph_accel.Gen.hr.E_FAIL,b.descr="HTTP "+c.t0.status),
500==c.t0.status&&(d=document.implementation.createHTMLDocument(""),d.documentElement.innerHTML=c.t0.responseText,d=d.body.textContent,d=seraph_accel.Gen.StrReplaceAll(d,"\r",""),d=seraph_accel.Gen.StrReplaceAll(d,["\t","\v"]," "),d=seraph_accel.Gen.StrReplaceAll(d,"\n",". "),(d=seraph_accel.Gen.StrReplaceAllWhileChanging(d,["  ",". . "],[" ",". "]).trim())&&"."!=d&&(b.descr+="<br>"+d));case 14:return c.abrupt("return",b);case 15:case "end":return c.stop()}},D,this,[[1,9]])}));return b.apply(this,
arguments)}function d(){d=_asyncToGenerator(_regenerator.mark(function D(b){var c,d,f,k,m,n,q,u,p,l,r,t=arguments;return _regenerator.wrap(function(g){for(;;)switch(g.prev=g.next){case 0:c=1<t.length&&void 0!==t[1]?t[1]:!1;d=jQuery(b.parentNode).closest(".blck").first();f=d.find(".seraph_accel_spinner");k=d.find('input[type="button"]:not(.cancel)');m=d.find('input[type="button"].cancel');n=d.find(".log");q=[{id:"3rdPartySettCompat",name:e("TestName_3rdPartySettCompat","admin.SelfDiag","seraphinite-accelerator")},
{id:"AsyncRequest",name:e("TestName_AsyncRequest","admin.SelfDiag","seraphinite-accelerator")},{id:"SetMaxExecTime",name:e("TestName_SetMaxExecTime","admin.SelfDiag","seraphinite-accelerator")},{id:"PageOptimize",name:e("TestName_PageOptimize","admin.SelfDiag","seraphinite-accelerator")},{id:"ExtCache",name:e("TestName_ExtCache","admin.SelfDiag","seraphinite-accelerator")},{id:"CronExec",name:e("TestName_CronExec","admin.SelfDiag","seraphinite-accelerator")}];n.empty();for(u=0;u<q.length;u++)p=q[u],
n.append(seraph_accel.Ui.LogItem("none",seraph_accel.Ui.Tag("strong",p.name?p.name:p.id),!1));if(!c){g.next=11;break}return g.abrupt("return");case 11:f.show(),k.prop("disabled",!0),m.prop("disabled",!1),seraph_accel.SelfDiag._int.inProgress=!0,u=0;case 16:if(!(u<q.length)){g.next=31;break}p=q[u];jQuery(n.children().get(u)).replaceWith(seraph_accel.Ui.LogItem("info",seraph_accel.Ui.Tag("strong",p.name?p.name:p.id)+e("TestRunning","admin.SelfDiag","seraphinite-accelerator"),!1));g.next=21;return a(p.id);
case 21:l=g.sent;r=e("TestSucc","admin.SelfDiag","seraphinite-accelerator");l.hr!=seraph_accel.Gen.hr.S_OK&&(r=seraph_accel.Gen.hr.Succ(l.hr)?l.hr==seraph_accel.Gen.hr.S_ABORTED?e("TestAbort","admin.SelfDiag","seraphinite-accelerator"):l.hr==seraph_accel.Gen.hr.S_FALSE?e("TestNotice","admin.SelfDiag","seraphinite-accelerator"):e("TestWarn","admin.SelfDiag","seraphinite-accelerator"):e("TestError","admin.SelfDiag","seraphinite-accelerator"));l.descr&&(r+="<br>"+l.descr);jQuery(n.children().get(u)).replaceWith(seraph_accel.Ui.LogItem(l.hr==
seraph_accel.Gen.hr.S_OK?"success":seraph_accel.Gen.hr.Succ(l.hr)?l.hr==seraph_accel.Gen.hr.S_FALSE?"normal":"warning":"error",seraph_accel.Ui.Tag("strong",p.name?p.name:p.id)+r,!1));if(seraph_accel.SelfDiag._int.inProgress){g.next=28;break}return g.abrupt("break",31);case 28:u++;g.next=16;break;case 31:f.hide(),k.prop("disabled",!1),m.prop("disabled",!0);case 34:case "end":return g.stop()}},D,this)}));return d.apply(this,arguments)}var e=seraph_accel.Wp.Loc.GetApi()._x;seraph_accel.SelfDiag={_int:{OnStart:function(a){return d.apply(this,
arguments)},OnCancel:function(a){a=jQuery(a.parentNode).closest(".blck").first();a.find(".seraph_accel_spinner");a.find('input[type="button"]:not(.cancel)');a.find('input[type="button"].cancel').prop("disabled",!0);seraph_accel.SelfDiag._int.inProgress=!1;seraph_accel.SelfDiag._int.curAjax&&seraph_accel.SelfDiag._int.curAjax.abort()},inProgress:!1}}})()})();
