var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");window.seraph_accel||(window.seraph_accel={});
(function(){seraph_accel.PluginAdmin={AdvertProductsContentInit:function(a,c,b,d,e,f){function m(a,b){var c="";var e=a.images;if(Array.isArray(e)){for(var f=-1,l=2147483647,m=-1,h=2147483647,g=0;g<e.length;g++){var k=e[g];if(b==k.width){f=g;break}b<k.width?(k=k.width-b,k<l&&(f=g,l=k)):(k=b-k.width,k<h&&(m=g,h=k))}e=-1!=f?e[f].url:-1!=m?e[m].url:null}else e=null;e&&(c+=seraph_accel.Ui.Tag("td",seraph_accel.Ui.Link(seraph_accel.Ui.Tag("img",null,{"class":"ctlSpaceAfter",width:b,src:e},!0),a.urlInfo,
!0),{style:{width:"1px"}}));c+=seraph_accel.Ui.TagOpen("td");c+=seraph_accel.Ui.Tag("h3",a.title,{"class":"ctlSpaceVAfter",style:{"margin-top":0}});c+=seraph_accel.Ui.Tag("div",a.descr);a.urlInfo&&(c+=seraph_accel.Ui.Button(d,!0,null,"ctlSpaceVBefore","button",{onclick:"window.open( '"+a.urlInfo+"', '_blank' )"}));c+=seraph_accel.Ui.TagClose("td");return seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",seraph_accel.Ui.Tag("row",c)))}function g(b,c){var d="";if(Array.isArray(b)&&b.length){d+=
seraph_accel.Ui.TagOpen("tr");for(var f=0;f<b.length;f++){var g=b[f];0<f&&0==f%e&&(d+=seraph_accel.Ui.TagClose("tr")+seraph_accel.Ui.TagOpen("tr"));d+=seraph_accel.Ui.Tag("td",seraph_accel.Ui.Tag("div",m(g,c),{style:{margin:"1em 1em 2em 1em"}}),{"class":"cx-lg-6 cx-xs-12",style:{"vertical-align":"top"}})}for(;f%e;f++)d+=seraph_accel.Ui.Tag("td",null,{"class":"cx-lg-6 cx-xs-12"});d+=seraph_accel.Ui.TagClose("tr");d=seraph_accel.Ui.Tag("table",seraph_accel.Ui.Tag("tbody",d))}jQuery(a).html(d)}jQuery.ajax({url:seraph_accel.Net.UpdateQueryArgs(c+
"/v1/advert_products",{slug:"accelerator",locale:b}),type:"GET",dataType:"json"}).then(function(a){g(a,f)},function(a){g(null,0)})},SwitchTo:function(a,c,b,d,e,f,m){function g(a,b){a?l.find(".operateblock").hide():l.find(".operateblock").find("*").prop("disabled",!1);h.removeClass("notice-warning updating-message");h.addClass(a?"notice-success updated-message":"notice-error");h.find("p").text(b);a&&l.find(".refresh_after").prop("checked")&&setTimeout(function(){location.reload()},0)}var l=jQuery(".seraph_accel_switchto"),
h=l.find(".update-message");h.removeClass("notice-success notice-error updated-message");h.addClass("notice-warning updating-message");h.find("p").text(c);l.find(".operateblock").find("*").prop("disabled",!0);h.show();jQuery.ajax({url:d,type:"post"}).then(function(b){return jQuery.ajax({url:e,type:"post",data:{action:"update-plugin",plugin:f,slug:"seraphinite-accelerator",_ajax_nonce:m,seraph_accel_switchto:a},dataType:"json"})}).then(function(a){a.success?g(!0,b):g(!1,a.data.errorMessage)},function(a){g(!1,
"OK"===a.statusText?"PHP error: "+a.responseText:"Backend error: "+a.status+" "+a.statusText)})},RateItCont_Set:function(a,c,b){var d=jQuery("#"+a),e=d.find(".actions"),f=d.find(".seraph_accel_spinner");e.hide();f.show();jQuery.ajax({url:b+"="+(c?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(a){d.hide()},function(a){e.show();f.hide()})},RateIt_Set:function(a,c){jQuery("#seraph_accel_RateIt_Message .actions").hide();jQuery("#seraph_accel_RateIt_Message .seraph_accel_spinner").show();
jQuery.ajax({url:c+"="+(a?"rateItPostpone":"rateItDisable"),type:"post"}).then(function(a){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_RateIt_Message"))},function(a){jQuery("#seraph_accel_RateIt_Message .actions").show();jQuery("#seraph_accel_RateIt_Message .spinner").hide()})},ChangeVersion_Confirm:function(a){jQuery("#seraph_accel_ChangeVersion_Msg .actions").hide();jQuery("#seraph_accel_ChangeVersion_Msg .seraph_accel_spinner").show();jQuery.ajax({url:a+"=changeVersionConfirm",type:"post"}).then(function(a){seraph_accel.Ui.BannerMsgClose(jQuery("#seraph_accel_ChangeVersion_Msg"))},
function(a){jQuery("#seraph_accel_ChangeVersion_Msg .actions").show();jQuery("#seraph_accel_ChangeVersion_Msg .spinner").hide()})},SettImport:function(a,c,b){function d(){f.prop("disabled",!1);e.hide()}if(b){a=jQuery(a.parentNode);var e=a.find(".seraph_accel_spinner"),f=a.find("input.button");f.prop("disabled",!0);e.show();a=new FileReader;a.onabort=function(a){d()};a.onerror=function(a){d()};a.onload=function(a){jQuery.ajax({url:c+"=settImport",type:"post",contentType:"application/json",data:a.target.result}).then(function(){location.reload()},
function(a){d()})};a.readAsText(b)}},SettExport:function(a,c){function b(a){a&&window.saveAs(new Blob([a],{type:"text/json"}),"seraphinite-accelerator-settings.json");e.prop("disabled",!1);d.hide()}a=jQuery(a.parentNode);var d=a.find(".seraph_accel_spinner"),e=a.find("input.button");e.prop("disabled",!0);d.show();jQuery.ajax({url:c+"=settExport",type:"post"}).then(function(a){seraph_accel.Ui.ScriptLoad(document,"https://cdn.jsdelivr.net/npm/file-saver@2.0.5/dist/FileSaver.min.js","file-saver").then(function(){b(a)},
function(a){b()})},function(a){b()})},OnSettWizNext:function(a,c){var b=jQuery(a).closest("form");a=jQuery(a.parentNode);var d=b.find(".wizPages");b=d.find(">.active").first();b.get(0)?(c=c?b.next():b.prev(),c.get(0)&&(b.removeClass("active"),b=c)):b=d.children().first();b.addClass("active");c=!!b.next().get(0);b=!!b.prev().get(0);a.find("input.next").prop("disabled",!c);a.find("input.prev").prop("disabled",!b);c?a.find("input.finish").hide():a.find("input.finish").show()}}})();
