var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(c){var k=0;return function(){return k<c.length?{done:!1,value:c[k++]}:{done:!0}}};$jscomp.arrayIterator=function(c){return{next:$jscomp.arrayIteratorImpl(c)}};$jscomp.makeIterator=function(c){var k="undefined"!=typeof Symbol&&Symbol.iterator&&c[Symbol.iterator];return k?k.call(c):$jscomp.arrayIterator(c)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,k,n){c!=Array.prototype&&c!=Object.prototype&&(c[k]=n.value)};
$jscomp.polyfill=function(c,k,n,p){if(k){n=$jscomp.global;c=c.split(".");for(p=0;p<c.length-1;p++){var m=c[p];m in n||(n[m]={});n=n[m]}c=c[c.length-1];p=n[c];k=k(p);k!=p&&null!=k&&$jscomp.defineProperty(n,c,{configurable:!0,writable:!0,value:k})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(c){function k(){this.batch_=null}function n(d){return d instanceof m?d:new m(function(f,a){f(d)})}if(c&&!$jscomp.FORCE_POLYFILL_PROMISE)return c;k.prototype.asyncExecute=function(d){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(d);return this};k.prototype.asyncExecuteBatch_=function(){var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})};var p=$jscomp.global.setTimeout;k.prototype.asyncExecuteFunction=function(d){p(d,
0)};k.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var d=this.batch_;this.batch_=[];for(var f=0;f<d.length;++f){var a=d[f];d[f]=null;try{a()}catch(b){this.asyncThrow_(b)}}}this.batch_=null};k.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var m=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var f=this.createResolveAndReject_();try{d(f.resolve,f.reject)}catch(a){f.reject(a)}};m.prototype.createResolveAndReject_=
function(){function d(b){return function(e){a||(a=!0,b.call(f,e))}}var f=this,a=!1;return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};m.prototype.resolveTo_=function(d){if(d===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(d instanceof m)this.settleSameAsPromise_(d);else{a:switch(typeof d){case "object":var f=null!=d;break a;case "function":f=!0;break a;default:f=!1}f?this.resolveToNonPromiseObj_(d):this.fulfill_(d)}};m.prototype.resolveToNonPromiseObj_=function(d){var f=
void 0;try{f=d.then}catch(a){this.reject_(a);return}"function"==typeof f?this.settleSameAsThenable_(f,d):this.fulfill_(d)};m.prototype.reject_=function(d){this.settle_(2,d)};m.prototype.fulfill_=function(d){this.settle_(1,d)};m.prototype.settle_=function(d,f){if(0!=this.state_)throw Error("Cannot settle("+d+", "+f+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=f;this.executeOnSettledCallbacks_()};m.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=
0;d<this.onSettledCallbacks_.length;++d)t.asyncExecute(this.onSettledCallbacks_[d]);this.onSettledCallbacks_=null}};var t=new k;m.prototype.settleSameAsPromise_=function(d){var f=this.createResolveAndReject_();d.callWhenSettled_(f.resolve,f.reject)};m.prototype.settleSameAsThenable_=function(d,f){var a=this.createResolveAndReject_();try{d.call(f,a.resolve,a.reject)}catch(b){a.reject(b)}};m.prototype.then=function(d,f){function a(a,h){return"function"==typeof a?function(h){try{b(a(h))}catch(w){e(w)}}:
h}var b,e,h=new m(function(a,h){b=a;e=h});this.callWhenSettled_(a(d,b),a(f,e));return h};m.prototype.catch=function(d){return this.then(void 0,d)};m.prototype.callWhenSettled_=function(d,f){function a(){switch(b.state_){case 1:d(b.result_);break;case 2:f(b.result_);break;default:throw Error("Unexpected state: "+b.state_);}}var b=this;null==this.onSettledCallbacks_?t.asyncExecute(a):this.onSettledCallbacks_.push(a)};m.resolve=n;m.reject=function(d){return new m(function(f,a){a(d)})};m.race=function(d){return new m(function(f,
a){for(var b=$jscomp.makeIterator(d),e=b.next();!e.done;e=b.next())n(e.value).callWhenSettled_(f,a)})};m.all=function(d){var f=$jscomp.makeIterator(d),a=f.next();return a.done?n([]):new m(function(b,e){function h(a){return function(e){d[a]=e;c--;0==c&&b(d)}}var d=[],c=0;do d.push(void 0),c++,n(a.value).callWhenSettled_(h(d.length-1),e),a=f.next();while(!a.done)})};return m},"es6","es3");
$jscomp.checkStringArgs=function(c,k,n){if(null==c)throw new TypeError("The 'this' value for String.prototype."+n+" must not be null or undefined");if(k instanceof RegExp)throw new TypeError("First argument to String.prototype."+n+" must not be a regular expression");return c+""};
$jscomp.polyfill("String.prototype.repeat",function(c){return c?c:function(c){var k=$jscomp.checkStringArgs(this,null,"repeat");if(0>c||1342177279<c)throw new RangeError("Invalid count value");c|=0;for(var p="";c;)if(c&1&&(p+=k),c>>>=1)k+=k;return p}},"es6","es3");
function _typeof(c){_typeof="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(c){return typeof c}:function(c){return c&&"function"===typeof Symbol&&c.constructor===Symbol&&c!==Symbol.prototype?"symbol":typeof c};return _typeof(c)}window.seraph_accel||(window.seraph_accel={});
(function(){function c(a,b){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,h=b.split(3<arguments.length&&void 0!==arguments[3]?arguments[3]:".").reduce(function(a,b){return"object"===_typeof(a)?a[b]:void 0},a);return void 0===h?e:h}function k(a){return"string"===typeof a?a:""}function n(a,b,e){if("string"!==typeof a)return a;if(Array.isArray(b)){for(var h=0;h<b.length;h++)a=n(a,b[h],Array.isArray(e)?e[h]:e);return a}"string"!==typeof b&&(b=""+b);"string"!==typeof e&&(e=""+e);if(a.replaceAll)return a.replaceAll(b,
e);for(h=0;;){h=a.indexOf(b,h);if(-1==h)break;a=a.substr(0,h)+e+a.substr(h+b.length);h+=e.length}return a}function p(a,b){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:void 0;if("string"===typeof b)return a.indexOf(b,e);if(!Array.isArray(b))return-1;var h=-1;for(d in b){var d=b[d];var c=a.indexOf(d,e);-1!=c&&(-1==h||h>c)&&(h=c)}return h}function m(a,b){var e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:void 0;if("string"===typeof b)return a.lastIndexOf(b,e);if(!Array.isArray(b))return-1;
var h=-1;for(d in b){var d=b[d];var c=a.lastIndexOf(d,e);-1!=c&&(-1==h||h<c)&&(h=c)}return h}function t(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0;if(!a||"object"!==_typeof(a))return a;var e=Array===a.constructor?[]:{};for(var h in a)e[h]=b?t(a[h]):a[h];return e}function d(a,b,e){if(void 0===b)return a;if(a&&a.constructor===Array){for(var h in b){var c=b[h];e&&void 0===c||a.push(c)}return a}for(h in b)c=b[h],e&&void 0===c||(a||(a={}),"object"===_typeof(c)&&"object"===_typeof(a[h])?
d(a[h],c,e):a[h]=c);return a}function f(a,b){function e(c,m){var k=h[c];if(!k){var u=b[c];if(!u){k="function"==typeof require&&require;if(!m&&k)return k(c,!0);if(d)return d(c,!0);throw Error('Cannot find module "'+c+'"');}k=h[c]={exports:{}};u[0].call(k.exports,function(a){var b=u[1][a];return e(b?b:a)},k,k.exports,f,a,b,h)}return k.exports}for(var h=2<arguments.length&&void 0!==arguments[2]?arguments[2]:{},d="function"==typeof require&&require,c=0;c<a.length;c++)e(a[c]);return e}seraph_accel.Gen=
{DoesFuncExist:function(a){return"function"===typeof c(window,a)},ParseCmdline:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,e=[];if("string"!=typeof a)return e;a=a.trim();for(var h=a.length,c=!1,d="",f=0;f<h;f++)" "!==a.charAt(f)||c?'"'===a.charAt(f)&&b?c=!c:d+=a.charAt(f):(e.push(d),d="");e.push(d);return e},GetFileName:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1;a=a.split("\\").pop().split("/").pop();b&&(b=a.lastIndexOf("."),-1!=b&&
(a=a.substr(0,b)));return a},GetFileDir:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:1;if(!e)return a;if(0<e)for(;;){var h=m(a,["/","\\"],h);if(-1==h||0==h)break;e--;if(!e)break;h--}else for(e*=-1;;){h=p(a,["/","\\"],h);if(-1==h)break;e--;if(!e)break;h++}return-1==h?"":a.substr(0,h+(b?1:0))},GetFileExt:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!1,e=a.lastIndexOf(".");return-1==e?
"":a.substr(e+(b?0:1))},CheckLastSlash:function(a){return"/"==k(a).substr(-1)},SetLastSlash:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:"/";if("string"!==typeof a||!a.length)return"";if(a.lastIndexOf(e)==a.length-1){if(!b)return a.substr(0,a.length-1)}else if(b)return a+e;return a},SetFirstSlash:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:!0,e=2<arguments.length&&void 0!==arguments[2]?
arguments[2]:"/";if("string"!==typeof a||!a.length)return"";if(0==a.indexOf(e)){if(!b)return a.substr(1)}else if(b)return e+a;return a},GetStr:k,StrReplaceAll:n,StrReplaceAllWhileChanging:function(a,b,e){if("string"!==typeof a)return a;for(;;){var h=a.length;a=n(a,b,e);if(h==a.length)break}return a},StrIndexOf:p,StrLastIndexOf:m,FilterObjectKeys:function(a){var b=1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:null,h={},c;for(c in a)e&&
-1!==e.indexOf(c)||b&&-1===b.indexOf(c)||(h[c]=a[c]);return h},DeepCopy:t,Extend:d,JsonParse:function(a){try{var b=JSON.parse(a)}catch(e){}return b},RegExpFromStr:function(a){var b=a.match(/^([\/~@;%#'])(.*?)\1([gimsuy]*)$/);return b?new RegExp(b[2],b[3].split("").filter(function(a,b,c){return c.indexOf(a)===b}).join("")):new RegExp(a)},GetObjField:c,SetObjField:function(a,b,c){var e=b.split(3<arguments.length&&void 0!==arguments[3]?arguments[3]:".");if(e.length){for(var d=0;d<e.length-1;d++){var f=
e[d];a[f]||(a[f]=d+1<e.length&&"+"==e[d+1]||"string"!==typeof f?[]:{});a=a[f]}f=e[e.length-1];"+"==f?"function"===typeof a.push&&a.push(c):a[f]=c}},GetObjContId:function(a){return n(JSON.stringify(a),'true false { } " : ,'.split(" "),"1      ".split(" "))},AsyncChain:function(){return new Promise(function(a,b){a()})},RunModules:f,EvalInCtx:function(a,b){if(a)return function(){return eval(a)}.call(b)},hr:{SEVERITY_SUCCESS:0,SEVERITY_ERROR:1,FACILITY_INTERNET:12,FACILITY_HTTP:25,S_OK:0,S_FALSE:1,S_FAIL:16389,
S_ABORTED:459975,E_NOTIMPL:2147500033,E_FAIL:2147500037,E_UNSUPPORTED:2147500065,E_INVALIDARG:2147942487,E_INVALID_STATE:2147947423,E_INTERNAL:2147943759,E_DATACORRUPTED:2147943792,E_NOT_FOUND:2147943568,E_ACCESS_DENIED:2147942405,E_ABORTED:2147943623,Make:function(a,b,e){return a<<31|b<<16|e&65535},Code:function(a){return a&65535},Facility:function(a){return a>>16&8191},Succ:function(a){return!(a&2147483648)},Fail:function(a){return!!(a&2147483648)}}};seraph_accel.Plugin={GetErrorDescr:function(a){var b=
1<arguments.length&&void 0!==arguments[1]?arguments[1]:null,e=2<arguments.length&&void 0!==arguments[2]?arguments[2]:!1,c=seraph_accel.Wp.Loc.GetApi(),d=c._x;c=c.sprintf;var f=c("Err_%08X",a),k=e&&seraph_accel.Gen.hr.Succ(a)?c("Err_%08X",seraph_accel.Gen.hr.Make(seraph_accel.Gen.hr.SEVERITY_ERROR,seraph_accel.Gen.hr.Facility(a),a)):null;e=[];b&&(e.push({id:f,ctx:b}),k&&e.push({id:k,ctx:b}));e.push({id:f,ctx:"admin.ErrDescr_Common"});k&&e.push({id:k,ctx:"admin.ErrDescr_Common"});e.push({id:"Def_%08X",
ctx:"admin.ErrDescr_Common"});for(var m in e)if(k=e[m],b=k.id,k=c(d(b,k.ctx,"seraphinite-accelerator"),a),k!=b)return k;return f},GetRootUrl:function(){return this._int.urlRoot},GetAdminApiUrl:function(){return this._int.urlAdminApi},_int:{urlRoot:"",urlAdminApi:""}};seraph_accel.Wp={Loc:{GetApi:function(){var a=null;a=window.wp&&window.wp.i18n?window.wp.i18n:{__:function(a,c){return seraph_accel.Wp.Loc._int.dcnpgettext(c,void 0,a)},_x:function(a,c,d){return seraph_accel.Wp.Loc._int.dcnpgettext(d,
c,a)},_n:function(a,c,d,f){return seraph_accel.Wp.Loc._int.dcnpgettext(f,void 0,a,c,d)},_nx:function(a,c,d,f,k){return seraph_accel.Wp.Loc._int.dcnpgettext(k,f,a,c,d)},sprintf:seraph_accel.Wp.Loc._int.sprintf};a.vsprintf||(a.vsprintf=function(c,d){return a.sprintf.apply(null,[c].concat(d||[]))});return a},SetData:function(a,c){return window.wp&&window.wp.i18n?window.wp.i18n.setLocaleData(a,c):seraph_accel.Wp.Loc._int.setLocaleData(a,c)},GetLang:function(){return seraph_accel.Wp.Loc._int.lang}}};(function(){function a(a){for(var c=
[],b=[],d,e,g;d=a.match(p);){e=d[0];for((g=a.substr(0,d.index).trim())&&c.push(g);g=b.pop();){if(n[e]){if(n[e][0]===g){e=n[e][1]||e;break}}else if(0<=m.indexOf(g)||k[g]<k[e]){b.push(g);break}c.push(g)}n[e]||b.push(e);a=a.substr(d.index+e.length)}(a=a.trim())&&c.push(a);return c.concat(b.reverse())}function c(c){var b=a(c);return function(a){a:{var c=[],d,e;for(d=0;d<b.length;d++){var h=b[d];if(e=t[h])try{var f=e.apply(null,c.splice(-1*e.length))}catch(l){a=l;break a}else f=a.hasOwnProperty(h)?a[h]:
+h;c.push(f)}a=c[0]}return a}}function d(a){var d=c(a);return function(a){return+d({n:a})}}function h(a){var c=a;if(v[c])c=v[c];else{for(var d=c,b,e=[],g=0;d;){if(null!==(b=q.text.exec(d)))e.push(b[0]);else if(null!==(b=q.modulo.exec(d)))e.push("%");else if(null!==(b=q.placeholder.exec(d))){if(b[2]){g|=1;var f=[],k=b[2],l;if(null!==(l=q.key.exec(k)))for(f.push(l[1]);""!==(k=k.substring(l[0].length));)if(null!==(l=q.key_access.exec(k)))f.push(l[1]);else if(null!==(l=q.index_access.exec(k)))f.push(l[1]);
else throw new SyntaxError("[sprintf] failed to parse named argument key");else throw new SyntaxError("[sprintf] failed to parse named argument key");b[2]=f}else g|=2;if(3===g)throw Error("[sprintf] mixing positional and named placeholders is not (yet) supported");e.push({placeholder:b[0],param_no:b[1],keys:b[2],sign:b[3],pad_char:b[4],align:b[5],width:b[6],precision:b[7],type:b[8]})}else throw new SyntaxError("[sprintf] unexpected placeholder");d=d.substring(b[0].length)}c=v[c]=e}d=arguments;b=1;
e=c.length;f="";var r,m;for(k=0;k<e;k++)if("string"===typeof c[k])f+=c[k];else if("object"===_typeof(c[k])){l=c[k];if(l.keys)for(g=d[b],r=0;r<l.keys.length;r++){if(void 0==g)throw Error(h('[sprintf] Cannot access property "%s" of undefined value "%s"',l.keys[r],l.keys[r-1]));g=g[l.keys[r]]}else g=l.param_no?d[l.param_no]:d[b++];q.not_type.test(l.type)&&q.not_primitive.test(l.type)&&g instanceof Function&&(g=g());if(q.numeric_arg.test(l.type)&&"number"!==typeof g&&isNaN(g))throw new TypeError(h("[sprintf] expecting number but found %T",
g));q.number.test(l.type)&&(m=0<=g);switch(l.type){case "b":g=parseInt(g,10).toString(2);break;case "c":g=String.fromCharCode(parseInt(g,10));break;case "d":case "i":g=parseInt(g,10);break;case "j":g=JSON.stringify(g,null,l.width?parseInt(l.width):0);break;case "e":g=l.precision?parseFloat(g).toExponential(l.precision):parseFloat(g).toExponential();break;case "f":g=l.precision?parseFloat(g).toFixed(l.precision):parseFloat(g);break;case "g":g=l.precision?String(Number(g.toPrecision(l.precision))):
parseFloat(g);break;case "o":g=(parseInt(g,10)>>>0).toString(8);break;case "s":g=String(g);g=l.precision?g.substring(0,l.precision):g;break;case "t":g=String(!!g);g=l.precision?g.substring(0,l.precision):g;break;case "T":g=Object.prototype.toString.call(g).slice(8,-1).toLowerCase();g=l.precision?g.substring(0,l.precision):g;break;case "u":g=parseInt(g,10)>>>0;break;case "v":g=g.valueOf();g=l.precision?g.substring(0,l.precision):g;break;case "x":g=(parseInt(g,10)>>>0).toString(16);break;case "X":g=
(parseInt(g,10)>>>0).toString(16).toUpperCase()}if(q.json.test(l.type))f+=g;else{if(!q.number.test(l.type)||m&&!l.sign)var n="";else n=m?"+":"-",g=g.toString().replace(q.sign,"");r=l.pad_char?"0"===l.pad_char?"0":l.pad_char.charAt(1):" ";var p=l.width-(n+g).length;p=l.width?0<p?r.repeat(p):"":"";f+=l.align?n+g+p:"0"===r?n+p+g:p+n+g}}return f}seraph_accel.Wp.Loc._int={data:{},pluralForms:{},options:{contextDelimiter:"\u0004"},lang:"",setLocaleData:function(a,c){a||(a=f);var b=this.data[c];if(b)for(var d in b)a[d]=
b[d];this.data[c]=a},dcnpgettext:function(a,c,b,d,e){this.data[a]||this.setLocaleData(void 0,a);e=void 0===e?0:this.getPluralForm(a,e);var g=b;c&&(g=c+this.options.contextDelimiter+b);return(a=this.data[a][g])&&a[e]?a[e]:0===e?b:d},getPluralForm:function(a,c){var b=this.pluralForms[a];if(!b){b=this.data[a][""];a:{var e;b=(b["Plural-Forms"]||b["plural-forms"]||b.plural_forms).split(";");for(e=0;e<b.length;e++){var f=b[e].trim();if(0===f.indexOf("plural=")){b=f.substr(7);break a}}b=void 0}b=this.pluralForms[a]=
d(b)}return b(c)},sprintf:h};var f={"":{plural_forms:"plural=(n!=1)"}};var k={"(":9,"!":8,"*":7,"/":7,"%":7,"+":6,"-":6,"<":5,"<=":5,">":5,">=":5,"==":4,"!=":4,"&&":3,"||":2,"?":1,"?:":1};var m=["(","?"];var n={")":["("],":":["?","?:"]};var p=/<=|>=|==|!=|&&|\|\||\?:|\(|!|\*|\/|%|\+|-|<|>|\?|\)|:/;var t={"!":function(a){return!a},"*":function(a,b){return a*b},"/":function(a,b){return a/b},"%":function(a,b){return a%b},"+":function(a,b){return a+b},"-":function(a,b){return a-b},"<":function(a,b){return a<
b},"<=":function(a,b){return a<=b},">":function(a,b){return a>b},">=":function(a,b){return a>=b},"==":function(a,b){return a===b},"!=":function(a,b){return a!==b},"&&":function(a,b){return a&&b},"||":function(a,b){return a||b},"?:":function(a,b,c){if(a)throw b;return c}},q={not_string:/[^s]/,not_bool:/[^t]/,not_type:/[^T]/,not_primitive:/[^v]/,number:/[diefg]/,numeric_arg:/[bcdiefguxX]/,json:/[j]/,not_json:/[^j]/,text:/^[^\x25]+/,modulo:/^\x25{2}/,placeholder:/^\x25(?:([1-9]\d*)\$|\(([^)]+)\))?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-gijostTuvxX])/,
key:/^([a-z_][a-z_\d]*)/i,key_access:/^\.([a-z_][a-z_\d]*)/i,index_access:/^\[(\d+)\]/,sign:/^[+-]/},v=Object.create(null)})()})();
